sudo: false
install:
  - curl -L https://github.com/raphink/travis-texlive/releases/download/2015-07-14_05/texlive.tar.xz | tar xJC ~
  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH
matrix:
  include:
  - env: BUILD=pdf DEPLOY=true
    script: make sagesse_lulu.pdf LATEX_INTERACTION="nonstopmode -halt-on-error"
  - env: BUILD=epub
    script: make sagesse_lulu.epub
  allow_failures:
  - env: BUILD=epub
deploy:
  provider: releases
  api_key:
    secure: TR2xilnOmKA59j1ZbVL893GKri+/Prke0ggQK58GusqciOZ80Dn6ikgeabvldc6MTrph/KsgpFdqdF5daWERtlR17u/l/SbJMT8m4h91XEAlKe19DP65k6qrt0NyI/miVXpAxUehvf0iAFN8wxQ8B2D7oraYTVz2m6tymDq5Tp4=
  file: sagesse_lulu.pdf
  on:
    tags: true
    all_branches: true
