# There is no TeX language
language: c
install:
  - sudo apt-get update
  - sudo apt-get install texlive-latex-extra texlive-publishers
  # scrjrnl was added in saucy
  - wget -O scrjrnl.cls http://www.tug.org/texlive/devsrc/Master/texmf-dist/tex/latex/scrjrnl/scrjrnl.cls
script: make sagesse_lulu.pdf LATEX_INTERACTION="nonstopmode -halt-on-error"
