# There is no TeX language
language: c
install:
  # TL2013 was added in saucy
  - sudo apt-add-repository -y ppa:texlive-backports
  - sudo apt-get update
  - sudo apt-get install texlive-latex-extra texlive-publishers
script: make sagesse_lulu.pdf LATEX_INTERACTION="nonstopmode -halt-on-error"
